amount_donated: 19177
number_families_supported: 28
number_months_support: 996
number_individuals_helped: 67
show_msk_medicine: true
show_new_msk_medicine: false
title_msk_medicine: Crash Courses - Coming Soon
text_msk_medicine: Currently under development.  Stay Tuned!
show_mini_podcasts: true
show_new_mini_podcasts: false
title_mini_podcasts: Coming Soon!
text_mini_podcasts: >-
  "Learn on the Go" with the new Mini-Podcasts Section.  These short, concise
  and clinically relevant podcasts will help improve your clinical skills and
  review key topics that are required for everyday primary care practice.